import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>BTB Best Practice Reference</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>BTB Best Practice Reference</h1>
      <p>
        This repo is made as a reference of a best-practice way to fresh start a{' '}
        <strong>Next.js</strong> project.
      </p>
    </>
  )
}
